{% set name = "lp_solve" %}
{% set version = "5.5.2.11" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name|lower }}_{{ version }}_source.tar.gz
    url: https://sourceforge.net/projects/lpsolve/files/lpsolve/{{ version }}/{{ name|lower }}_{{ version }}_source.tar.gz
    sha256: 6d4abff5cc6aaa933ae8e6c17a226df0fc0b671c438f69715d41d09fe81f902f

build:
    number: 0


requirements:
    build:
      - cmake
      - ninja
      - {{ compiler('c') }}
    host:

test:
  commands:
    - lp_solve -h
    - test -f ${PREFIX}/include/lpsolve/lp_lib.h  # [unix]
    - test -f ${PREFIX}/lib/liblpsolve55${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\lpsolve\\lp_lib.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\lpsolve55.dll exit 1  # [win]

about:
    home: http://lpsolve.sourceforge.net/5.5/
    summary: lp_solve is a Mixed Integer Linear Programming (MILP) solver
    license: LGPL-2.1-only
    license_file: '{{ environ["RECIPE_DIR"] }}/lgpl-2.1.txt'

extra:
    recipe-maintainers:
      - jschueller
      - mictadlo
