{% set name = "lp_solve" %}
{% set version = "5.5.2.5" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name|lower }}_{{ version }}_source.tar.gz
    url: https://sourceforge.net/projects/lpsolve/files/lpsolve/{{ version }}/{{ name|lower }}_{{ version }}_source.tar.gz
    md5: 3be57261fc41dd8e210f54017220d5f7

build:
    number: 1001


requirements:
    build:
      - cmake
      - make  # [unix]
      - {{ compiler('c') }}
    host:

test:
  commands:
    - lp_solve -h
    - test -f ${PREFIX}/include/lpsolve/lp_lib.h  # [unix]
    - test -f ${PREFIX}/lib/liblpsolve55${SHLIB_EXT}  # [unix]
    - if not exist %PREFIX%\\Library\\include\\lpsolve\\lp_lib.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\lpsolve55.dll exit 1  # [win]

about:
    home: http://lpsolve.sourceforge.net/5.5/
    summary: lp_solve is a Mixed Integer Linear Programming (MILP) solver
    license: LGPL
    license_file: '{{ environ["RECIPE_DIR"] }}/lgpl-2.1.txt'

extra:
    recipe-maintainers:
      - jschueller
      - mictadlo
