{% set name = "lp_solve" %}
{% set version = "5.5.2.5" %}

package:
    name: {{ name|lower }}
    version: {{ version }}    

source:
    fn: {{ name|lower }}_{{ version }}_source.tar.gz
    url: https://sourceforge.net/projects/lpsolve/files/lpsolve/{{ version }}/{{ name|lower }}_{{ version }}_source.tar.gz
    md5: 3be57261fc41dd8e210f54017220d5f7

build:
    number: 0
    skip: True  # [win and py36]
    features:
      - vc9  # [win and py27]
      - vc14  # [win and py>=35]


requirements:
    build:
      - toolchain
      - cmake  # [win]

    run:
      - libgcc  # [linux]

test:
    requires:
      - python {{ os.environ.get('PY_VER', '') + '*' }}  # [win]
    files:
      - demo.c
    commands:
      - lp_solve -h
 
about:
    home: http://lpsolve.sourceforge.net/5.5/
    summary: lp_solve is a Mixed Integer Linear Programming (MILP) solver
    license: LGPL
    license_file: '{{ environ["RECIPE_DIR"] }}/lgpl-2.1.txt'

extra:
    recipe-maintainers:
      - mictadlo
