travis:
  secure:
    BINSTAR_TOKEN: Y0uKZi1YZqLrJ5+cGayCtXnG03rFrAyj9tYKilsH83Ya0rTjFY088v6zNJqw0HhH+LodhXXLqoXD0e0JdseZvnCimbpcEUvbNaq2In6tByGeqIwYzpeUt/389MxE3ckd9rtXYpEePHuXCNRPmYUYXseRVHKoVaqy9OEEIFJLG96+IfqO3j6HHJQGcWFD7112218ALsA1p4GMwa/GXHhlivTuILZ9VFhzcWCuW/x26mjg9Kb0OkNKDheIYbeM2kBw9T6oCSe7ukyhAaIQ4DvBloifTCqUcUz2aOS6gKzLjpTaeGen/EI1UbTfWDmod/uhn/e1qlPUuUw/4VTPr2M4/wgUZCd9dnRuY8nM+UjoPSKX2Hs2iEXKdOoFSIgJIQISFr4llW5VvJEbYFMrV2OhmdLNUBV/cNIg7sUdKH1b3ZvVxpahsG9RyTlUVFzg2Y5kxRSOiLo0/0MpE0pNxjJQNQnoBtJzqWnMQCEYpjxXaXmxnx/3ts5ASHRritPm62+/BXFG6We3wQ9Y30tc9VFhFejjBFZdrrVKFTmSpHh/7Ok8crb5bCciYZStRqYPS9wr6iGgUGnsG+EJGBuklRiGPByxfez/xZ8DITN47c6VSdwta7mD9QklObMa4GjkwT+EJz5pneSz/drah7odcFwkaUXd2BOpPEpfgiQZ1J0Qud4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
