travis:
  secure:
    BINSTAR_TOKEN: D9CWHw00G/5p0zmP2iiZ36H8Ml+kWIWAPTrIuIUk2XZYUy4q9tYQnUhuYFQ5jK1r+xG5BSaAWCet3NO0ogARC7VKwnpE329+VMTMVQi0i282KBDYIKy8xJrE4Yqf6/rRK68M4s8eqUoPXkvxGKDf4jlhPTe5s975z4KVdBTOAaUcq76CZIKqeIL8OgL7JVdAI1MqoponkVVeCypaM9KlxJMsArGuUoI03xn0JrdM1DcHX9lljTawXdrkDd1uCuIgGh5ZqTAwmO5QpldosJxPgnYiDMhFoo1Ln80FRxnQ0EOHmRr42QrxbdqWBMYb2T6xqNXF56nk7Zgw312CUoWJlURZsP+7vTnvuKVpSlSFhzX8W/0UWc4GGk/TkBslvWctCYVh3mo7tBJ7GBsJya1BqksqLno9WssdUOCFdavaMZCWh2Xa0vNlsqj1bItoxe6lfMaIHagvm5/SjHw9DEp6rjCVZRT0fXpp+aeVuRtHyOiFfLl4ifQm5CoWrIH/c/wjw/0W1SCx9gINjvotcDdP8IoI5w7WywRlkpDM07o3CIYoVeytC4SIgrhPMZYUe5ZeL+7ECMseS0bo8C6x0SJGqN7Q5F8St+zd1S9lsAqq/vpo8gb+lnysG2elNMpxhnZcKoKSeuS+hIl1yRe+V7w5IgVIu1KjvDtTnpgX/6Vl69s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
