travis:
  secure:
    BINSTAR_TOKEN: kYBrJXzq5OSlSjgb2flgPSI7pLbxEuEwdajvOvergBjH7HIMiFq2EQiJSX5dZruip3xGuEtQ5kvuraGh7TeRO3mnTHuSPhIQDTsIiEoUwCBNfLn67AVKl9RK2yBxak9PYzyWz94cjb4te7BcyaDimTUe9LLeqkf5TyoBatxvUN6Su1xy/8SsJ4iHL2nXNP5FtEz8+aoLpFe9vwaaPHQsMntl5216L/EHAwEWsvQQO1i087/Kr9Zdwi2/fXJ6MwGHsAdAJXgHIr2APbf5AUut6FedWU+r3webK10fRfkeLBfZPe1nigjsPMwAFldzMpqiSc6gXqh08t5SeNPOTPUjsqsYGzM2/RvtUAOOTtIU4WwT6kb6XEdlxSOgh5JugjAh7IrflbDSis2CiYOxCgYH0KXI+7nHzsj42ct7sSB6+wEHQIEW3raOWjupSNRRGTwmPURH0XvdlFOtB8W9KZktW+JCi0in7LIXFdp0nypfka/vE0n4WK2akoGyprRvct4AOEW9KTMcb6+0KLiU9yR4qP8Ezgjott3LOIH0jet9emLoP71K3CKVAl2cXqdpqzfmuYbB0zkIR0giJ/ywfjX2r2dA6xLc1F1NvyiYh2T9ML/U5cMThBCuI26Z3PWedzxS7vY17UjK8GPgnaT0rqplqKglTyp6ybnhHEcCK8S4Eug=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
