travis:
  secure:
    BINSTAR_TOKEN: gzC0voNbXYA+Kg1uWpWQeOgZCpFEINnRdrM+EFzeX3CdBwK1SpjVPgdsLTs247jcPpixdOes0msfmTL0HD0j6ceTCuXNs5c15aqxce+yg9V1kPVBb+AjgmQ0LtSZQYWDppK+N660tDzyN0BNOqDPBmkb6WXjuQ0x9OQILa239V47vmHRABd8gkw71KeiZ5B5ragUcJbehw0BK5SnTHKK63iNAjegIFaICN3hdFrHHtCOf7EAF5XhI17kQe7oDQVUlMMleYIzqlxFPoLEYjPvqxI/u1iDfTqi2YCXQtyuzYRu4oG/s+JLdjuJ77mNYq87Sgyo9IN717CZ5y3BQjRr9tSf7P31uD/NTKoYPzVjgRfSDZkqlQ/gZMJvlddr7YLmsgsUIAxFqHIuO1x74ijbgN0pH8nGNFbSJ7QwvfYQL9OaDXX3+59skq2WYdWAkWSv8N/49r5djDy1uVpfoa2yycX/8azugt25OmIdUEOyGcF7zzBCM2slz8WUr7NGGx0FB3W5eqo724LNJ8XoSMA9/ZqMosgV0DUrSRi7ti471R2ebvOkOwkUYaAHRfA5l4cMI+LnBpfpDsx6U0ldeFOe9vBG+34VZ/BT4dw/TsgG/AHuCE7DmnBzPwXdWk/T7d7f3Rwerxg4HSpqVi7/bqnLBHIBX7gO6O22isefj1I4AZU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
