appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: FZpdnFhUJpAry/T+GoEAK4UoJw2/fYHTndRjLQHqpkYzHfBuAL38d5M9sB4bWySLqCle5rWcVwMlTS2Qlzz3epqb6DWwHgT6PjXdbD7WagDsD1KU0Cd3IuRE6muEwUJkCAfsI8WYPm1tjUSBezSkYIzXFajQgX9xVO9DO5ejtMixZTZ7c9gnVFFULGw4zNlSkhfZBMf3rgFOiX3+6jMo55f9tCi1Dck6AWM2HiYRFJPtcCgZX5rfqFhISWbRbyzVZYDNPXakzcFERoRRhz8GjACxCpaSinVvYXY6hP3zRLG52qPMGErhN0Yi7AQ6qjao601RnEouw9meBxTms/DKqQZ1Z6Nn+kYon6G6lu/yPF97PEIunoOjQhie2gARJog7jvsoL7O7bAEv2FVUs2u1TD4UnfxpvyiLfXuj1c6z6Dz2XAhAbJTa29FdLOK9MkbUf1PHSu8Vno07QnJvhdV1uOU6KS5MExnEKsYuIoo+zCM+Ku+HZhNf009N0tSsCCempovwO9FZVAhD/LgyR4YLhfPTM7MjEdYAkZdPGHTAnq+kh0qkJL0ipw5IJf/PfB1WzPJMNj+gX6Vhza1D66l5DncJ6+Ht2pbPAUee/TFC8CcKH/P81Y0Jx+rE7SGLWQx9sbD38zDooce0d0VL7/of8Kbwo112XWM3VPqD0Ks974A=}
